/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacionxml;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Wilmer
 */
public class Fact_ResumenGastos extends javax.swing.JFrame {

    private Object viviendaField;

    /**
     * Creates new form Fact_ResumenGastos
     */
    public Fact_ResumenGastos() {
        initComponents();
    }
    DefaultTableModel listFacturasUsuario = new DefaultTableModel();
    double[] gastosTotales = new double[7];
    String[] nombreGastos = new String[7];
    double[] maximoGastos = new double[7];
    private Connection connectionBaseProyectoLibres = null;

    private void CrearTabla() {

        listFacturasUsuario.addColumn("CODIGO");
        listFacturasUsuario.addColumn("CEDULA");
        listFacturasUsuario.addColumn("RUC");
        listFacturasUsuario.addColumn("FECHA");
        listFacturasUsuario.addColumn("TOTAL_SIN_IVA");
        listFacturasUsuario.addColumn("IVA");
        listFacturasUsuario.addColumn("TOTAL_CON_IVA");
        listFacturasUsuario.addColumn("VIVIENDA");
        listFacturasUsuario.addColumn("ALIMENTACION");
        listFacturasUsuario.addColumn("SALUD");
        listFacturasUsuario.addColumn("EDUCACION");
        listFacturasUsuario.addColumn("VESTIMENTA");
        listFacturasUsuario.addColumn("OTROS");
        listFacturasUsuario.addColumn("NUMERO_FACTURA");

    }

    private void conectarAbaseProyectoLibres() {
        try {
            connectionBaseProyectoLibres = DriverManager.getConnection("jdbc:mysql://localhost:3306/libresfacturaproyecto", "root", "basQUET23");
            System.out.println("Connection OK!");
        } catch (SQLException e) {
            System.out.println("Connection Failed! Check output console");
            e.printStackTrace();
            return;
        }
    }

    public void sumar() {
        int totalRow = detalleGastosJtable.getRowCount();
        totalRow -= 1;
        int index = 0;
        for (int j = 7; j < 13; j++) {
            double sumatoria = 0;

            for (int i = 0; i <= (totalRow); i++) {
                gastosTotales[i] = gastosTotales[i] + Double.parseDouble(String.valueOf(detalleGastosJtable.getValueAt(i, j)));
                sumatoria = sumatoria + Double.parseDouble(String.valueOf(detalleGastosJtable.getValueAt(i, j)));

            }

            nombreGastos[index] = detalleGastosJtable.getColumnName(j);
            index++;
//            JOptionPane.showMessageDialog(null, "total_" + detalleGastosJtable.getColumnName(j) + ":" + sumatoria);
        }
        cargarListaGastos();
    }

    private void cargarListaGastos() {
        cargarMaximoGastos(valorFBD);
        DefaultListModel modelo = new DefaultListModel();
        DefaultListModel modeloGastos = new DefaultListModel();
        String[] totalesNombre = new String[7];
        for (int i = 0; i < 6; i++) {
            totalesNombre[i] = nombreGastos[i] + "=" + gastosTotales[i];
            modelo.addElement(nombreGastos[i]);
            modeloGastos.addElement(maximoGastos[i]);
        }
        totalesTipoGasto.setModel(modelo);
        montoMaximo.setModel(modeloGastos);
        totalesTipoGasto.setListData(totalesNombre);
    }

    private void cargarMaximoGastos(double FBD) {
        maximoGastos[0] = 0.325 * FBD;
        maximoGastos[1] = 0.325 * FBD;
        maximoGastos[2] = 1.3 * FBD;
        maximoGastos[3] = 0.325 * FBD;
        maximoGastos[4] = 0.325 * FBD;
        maximoGastos[5] = 0.325 * FBD;
        
    }

    public void cargarTabla(String CI) {
        System.out.println("ci" + CI);
        conectarAbaseProyectoLibres();
        CrearTabla();
        try {
            Statement st = connectionBaseProyectoLibres.createStatement();
            ResultSet rs = st.executeQuery("SELECT * FROM Factura f WHERE f.cedula ='" + CI + "'");
            while (rs.next()) {
                Object dato[] = new Object[14];
                for (int i = 0; i < 13; i++) {
                    dato[i] = rs.getString(i + 1);
                    System.out.println("dato" + dato[i]);
                }
                listFacturasUsuario.addRow(dato);

            }
            this.detalleGastosJtable.setModel(listFacturasUsuario);
        } catch (Exception e) {
            System.out.println("error" + e.toString());
        }
        sumar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jDialog1 = new javax.swing.JDialog();
        menuBar1 = new java.awt.MenuBar();
        menu1 = new java.awt.Menu();
        menu2 = new java.awt.Menu();
        jScrollPane1 = new javax.swing.JScrollPane();
        detalleGastosJtable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        totalesTipoGasto = new javax.swing.JList();
        jScrollPane3 = new javax.swing.JScrollPane();
        montoMaximo = new javax.swing.JList();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        menu1.setLabel("File");
        menuBar1.add(menu1);

        menu2.setLabel("Edit");
        menuBar1.add(menu2);

        detalleGastosJtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(detalleGastosJtable);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Resumen gastos");

        jScrollPane2.setViewportView(totalesTipoGasto);

        jScrollPane3.setViewportView(montoMaximo);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setText("TIPO DE GASTO");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setText("MONTO MÁXIMO");

        jButton1.setText("REGRESAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jMenu1.setText("Archivo");

        jMenuItem1.setText("Ingresar Fracción básica desgravada (FBD)");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("salir");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(227, 227, 227)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addGap(42, 42, 42)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 197, Short.MAX_VALUE)
                                        .addComponent(jButton1)))))
                        .addGap(45, 45, 45)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                .addGap(33, 33, 33)
                .addComponent(jLabel2)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jButton1))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.hide();
    }//GEN-LAST:event_jButton1ActionPerformed
    double valorFBD = 11170;
    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        String respuesta = JOptionPane.showInputDialog("Escriba valor Fracción básica desgravada ");
        valorFBD = Double.parseDouble(respuesta);
        cargarMaximoGastos(valorFBD);
        cargarListaGastos();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Fact_ResumenGastos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Fact_ResumenGastos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Fact_ResumenGastos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Fact_ResumenGastos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Fact_ResumenGastos().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable detalleGastosJtable;
    private javax.swing.JButton jButton1;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private java.awt.Menu menu1;
    private java.awt.Menu menu2;
    private java.awt.MenuBar menuBar1;
    private javax.swing.JList montoMaximo;
    private javax.swing.JList totalesTipoGasto;
    // End of variables declaration//GEN-END:variables
}
